### ISSUE TITLE
AT101 payload and decoder incorrectly uses positive longitude for West

### ISSUE THREAD

**Issue by danak6jq** [Milesight-IoT/SensorDecoders#33]
I'm located in California, near 38.169N and 122.137W. By convention, southern latitudes and western longitudes are given a negative sign, so this should be:

38.169, -122.137

However, the AT101 payload and decoded value shows 38.169, 122.137.

If I give this string to Google Maps, it shows the correct location in California:

<img width="413" alt="image" src="https://github.com/Milesight-IoT/SensorDecoders/assets/942815/8396aa2b-fef1-4321-ad41-56e9a8a88cac">

However, the AT101 payload and decoded value shows 38.169, 122.137, which is in the sea between China and Korea:

<img width="240" alt="image" src="https://github.com/Milesight-IoT/SensorDecoders/assets/942815/752f6701-3877-4820-a5a3-b6eeaeb25529">

Perhaps the decoder should multiply the longitude by -1 ?

**Comment by milesight-sway** [comment]
what's the raw payload data?

**Comment by danak6jq** [comment]
Raw payload in hex here:
<img width="748" alt="image" src="https://github.com/Milesight-IoT/SensorDecoders/assets/942815/dac486d9-9469-43ee-8741-2effe082347b">

Decoded payload here, along with raw payload in base64
<img width="248" alt="image" src="https://github.com/Milesight-IoT/SensorDecoders/assets/942815/1d9f4bcf-7f22-4877-aae5-0ca7c185f094">

The Chirpstack v4 decoder:
<img width="366" alt="image" src="https://github.com/Milesight-IoT/SensorDecoders/assets/942815/81cd6b25-c623-4fe1-9079-2df2ec116927">

Source for the decoder:
https://github.com/Milesight-IoT/SensorDecoders/blob/main/AT_Series/AT101/AT101_Chirpstack_v4.js

You can manually decode the payload like I did and confirm I'm seeing a positive longitude value in the AT101
payload; the decoder is just converting that correctly.

**Comment by danak6jq** [comment]
> 1. What's the raw data?
> 2. What decoder are you using?

Could you share raw payloads from China? Perhaps the longitude completely lacks E/W sign?

**Comment by milesight-sway** [comment]
What is the firmware version of the AT101?

ToolBox App
- iOS (https://apps.apple.com/us/app/milesight-toolbox/id1518748039)
- Android (https://play.google.com/store/search?q=milesight+toolbox&c=apps)

**Comment by milesight-sway** [comment]
Upgrade AT101 firmware using ToolBox App. 
[AT101.0000.0100.0101-r1.zip](https://github.com/Milesight-IoT/SensorDecoders/files/13484231/AT101.0000.0100.0101-r1.zip)

**Comment by danak6jq** [comment]
> What is the firmware version of the AT101?
> 
> ToolBox App
> 
> * iOS (https://apps.apple.com/us/app/milesight-toolbox/id1518748039)
> * Android (https://play.google.com/store/search?q=milesight+toolbox&c=apps)

![image](https://github.com/Milesight-IoT/SensorDecoders/assets/942815/c88a798a-478e-435a-8f55-0cdf6d07f0ca)

**Comment by danak6jq** [comment]
> Upgrade AT101 firmware using ToolBox App. （rename .zip -> .bin） [AT101.0000.0100.0101-r1.zip](https://github.com/Milesight-IoT/SensorDecoders/files/13484231/AT101.0000.0100.0101-r1.zip)

Upgraded firmware, here's the first report - seems to have addressed this issue. Will this firmware be released normally?

Thank you!

<img width="191" alt="image" src="https://github.com/Milesight-IoT/SensorDecoders/assets/942815/a35af90a-d219-4db2-a093-404fef558164">

**Comment by danak6jq** [comment]
I do see battery level of 1%, which might be my fault (I had difficulty upgrading the firmware over NFC, seemed to brick the AT101, removed the batteries, was eventually successful with BLE).

It's possible the battery report will correct itself?

**Comment by milesight-sway** [comment]
The firmware file is a beta version.

Regarding the battery problem, try removing the battery for a while and then reinstalling it and expect that to solve your problem!

**Comment by danak6jq** [comment]
> The firmware file is a beta version.
> 
> Regarding the battery problem, try removing the battery for a while and then reinstalling it and expect that to solve your problem!

That resolved the issue - 30 minutes no batteries, I now get correct reports.

Any idea when this beta firmware build will be in release?

Thank you!

**Comment by milesight-sway** [comment]
Yes.

We appreciate your feedback to help us make our product even better.
