### ISSUE TITLE
Encoder for WT201

### ISSUE THREAD

**Issue by dumiller** [Milesight-IoT/SensorDecoders#39]
We are looking for the encoder for the WT201 to write data such as the temperature set point, fan speed and mode. Is there an encoder available Will the encore for the WT30x work?

**Comment by milesight-sway** [comment]
Sorry about that. Coming soon. 

Right now, Please checkout feat/wt201-humidy

**Comment by milesight-sway** [comment]
This feature has been successfully merged into the main branch, and we will now close this issue. If you encounter any other problems, don't hesitate to open an issue.
