### ISSUE TITLE
EM-300 payload without battery value?

### ISSUE THREAD

**Issue by KLMTechPeterHuisman** [Milesight-IoT/SensorDecoders#4]
As payload for the EM-300-TH sensor I am receiving: 
0367AD00046873

Per the decoder in github, the temperature and humidity can be decoded, but it seems that the payloadstring lacks the battery value.

Is the payload format changed with firmware 1.2, so that battery is no longer a part of the payload?

**Comment by Milesight-IoT** [comment]
Hi thank you for testing Milesight products.
EM300 series sensor only sends battery level data when joining the network or every 6 hours. This inerval is fixed and not support change.
