### ISSUE TITLE
Encoder for WT101

### ISSUE THREAD

**Issue by vigalent** [Milesight-IoT/SensorDecoders#40]
Can you please post the encoder for the WT101 to allow writing of target temperature, control mode and position?

**Comment by milesight-sway** [comment]
checkout [feat/wt101-encode](https://github.com/Milesight-IoT/SensorDecoders/blob/feat/wt101-encode/WT_Series/WT101/WT101_Encoder.js)

**Comment by milesight-sway** [comment]
This feature has been successfully merged into the main branch, and we will now close this issue. If you encounter any other problems, don't hesitate to open an issue.
