### ISSUE TITLE
get devEUI inside the decoder

### ISSUE THREAD

**Issue by salembream** [Milesight-IoT/SensorDecoders#42]
Hello,

I'm testing the UG56 GW, to get data from em300-DI sensors, with custom decoder (copied from this github repo).
My system/application receive the data through the MQTT interface in the gateway.

the issue is that the received MQTT message is the same as the decoder output which does not include the devEUI.
so my question, is there a way to read/know the devEUI within the decoder, so we can add it to the output message?

**Comment by mscloud-1** [comment]
READ: https://github.com/Milesight-IoT/SensorDecoders/blob/main/LoRaObject.md
- `LoRaObject.devEUI`

**Comment by milesight-sway** [comment]
READ: https://github.com/Milesight-IoT/SensorDecoders/blob/main/LoRaObject.md
- `LoRaObject.devEUI`
