### ISSUE TITLE
Problem decoding up messages in EM300DI

### ISSUE THREAD

**Issue by isabido** [Milesight-IoT/SensorDecoders#43]
HI, we are integrating this EM300-DI device into Chirpstack 4.8.1, after loading the decode that you have published.

https://github.com/Milesight-IoT/SensorDecoders/blob/main/EM_Series/EM300_Series/EM300-DI/EM300-DI_Decoder.js

I have a configuration where the totalizer of a water meter is sent every minute.

And I get these error messages randomly due to decoding failure.
![image](https://github.com/Milesight-IoT/SensorDecoders/assets/559650/ffdbc297-50e5-4852-b16f-404ab5afea68)

Here is an image of a UP that cannot decode
![image](https://github.com/Milesight-IoT/SensorDecoders/assets/559650/63b18f9a-181b-4275-8a40-9886d61602ad)

And here is an image of a UP that decodes correctly
![image](https://github.com/Milesight-IoT/SensorDecoders/assets/559650/15211aac-4c14-453c-99c8-f1307528d49b)

[EM-300-DI.log.json](https://github.com/user-attachments/files/15920452/EM-300-DI.log.json)

I am attaching a more complete log where you can see UP messages correctly decoded and others that are not.

What could be happening?

thanks for your help

**Comment by danak6jq** [comment]
@isabido could you please copy and paste the _text_ of the 'data:' item from the two UPs? I'd rather not type them in and perhaps have an error.

This:
![image](https://github.com/Milesight-IoT/SensorDecoders/assets/942815/c5abe610-406d-451e-bb96-0bda25063e96)

and this:
![image](https://github.com/Milesight-IoT/SensorDecoders/assets/942815/00503eb6-cd8b-42c0-99ca-83143e35d937)

Thank you -
Dana

**Comment by isabido** [comment]
Hi Dana, 

Thank you for your help, sorry I sent the image of the same package, it was a mistake, I'll give you this new example that is about the same thing.

![image](https://github.com/Milesight-IoT/SensorDecoders/assets/559650/84365c5c-3f0e-4479-b847-3098ce70eb2e)


This would be the one that returns the error 
data:"AXVkA2cYAQRoZQXhCgAKAAA0skY="
![image](https://github.com/Milesight-IoT/SensorDecoders/assets/559650/3fc1cec5-52d5-4554-8960-6f730f4fcb70)

And this one that sends the next minute would be correct
data:"AXVkA2cZAQRoZAXhCgAKAAA0skY="
![image](https://github.com/Milesight-IoT/SensorDecoders/assets/559650/ac3b7065-cfd7-49cc-b3cd-37834f38a819)

**Comment by milesight-sway** [comment]
It appears you have already reached out to our technical support team. We will go ahead and close this issue.

The decoding function for the EM300-DI is working without any problems.

**Comment by danak6jq** [comment]
Just to complete my comments - I manually decoded the "good" and "bad" payloads and they're both good, in fact nearly identical. Glad you're getting it resolved.
