### ISSUE TITLE
Downlink Encoder

### ISSUE THREAD

**Issue by Sleeper67** [Milesight-IoT/SensorDecoders#47]
Hi there,

Is there a Downlink encoder? 

My use case here is to SET the spreading factor on a EM320 via downlink, so just wondering if there is a spreadsheet template or similar to make a downlink.

**Comment by milesight-sway** [comment]
Sorry, LoRaWAN parameters cannot be configured via downlink. 

The downlink settings include reporting interval, collection interval, device reboot, historical data transmission, and so on.

**Comment by Sleeper67** [comment]
That's a shame, but thanks for the encoder. 

I did look but wasn't able to see this before
