### ISSUE TITLE
CT101 decoder error...

### ISSUE THREAD

**Issue by AngeLinuX99** [Milesight-IoT/SensorDecoders#49]
Hi forum 

I'm Using your CT101 decoder, but is not reporting Product Serial Number, Hardware version and firmware version. only i get

ipso_version:"v0.1"
power:"on"

Please, can you review the decoder to show all basic information ? 

Sensor Data is reporting ok.

Best Regards

**Comment by milesight-sway** [comment]
Providing the raw Payload data will enable me to swiftly pinpoint and address any issues.
