### ISSUE TITLE
VS350 Passage People Counter 

### ISSUE THREAD

**Issue by JCIQB** [Milesight-IoT/SensorDecoders#55]
Hi,

Existing encounter some issue with the VS350 Passage People Counter installed at 4 locations and the data counting is inaccurate with low count at all the locations. Conduct the physical people counting and compare with the data from the sensors is not tally. 

Sensor is installed as per instruction for VS350, however the base on the observation at 1 of the location. Sensor did not detect the people movement in/out from the data retrieve in the system. 

Could someone advise or encountered this issue before to share how to resolve this!

Thank you.

**Comment by milesight-sway** [comment]
Please contact Support Team for more help. (This repo is only for Sensor Codec issues)

1. go to https://support.milesight-iot.com/support/home
2. create a new ticket
