### ISSUE TITLE
Missing Decoder GS601

### ISSUE THREAD

**Issue by Sleeper67** [Milesight-IoT/SensorDecoders#57]
Hi there, 

Can the Decoder/Encoder please be uploaded for the **GS601**

Thanks

**Comment by milesight-sway** [comment]
- feat/gs601 (https://github.com/Milesight-IoT/SensorDecoders/tree/feat/gs601/GS_Series/GS601)

**Comment by Sleeper67** [comment]
Thanks @milesight-sway
