### ISSUE TITLE
Encoders for WS558 and WS52X

### ISSUE THREAD

**Issue by Sleeper67** [Milesight-IoT/SensorDecoders#58]
Hi there,

Could I please have access to the 'Encoders' for Downlinks for the WS558 and WS52X

Thank you

**Comment by milesight-sway** [comment]
- feat/ws558 (https://github.com/Milesight-IoT/SensorDecoders/tree/feat/ws558/WS_Series/WS558)
- feat/ws52x (https://github.com/Milesight-IoT/SensorDecoders/tree/feat/ws52x/WS_Series/WS52x)

**Comment by Sleeper67** [comment]
Thanks @milesight-sway
